In [2]:
import pandas as pd

In [3]:
import pandas as pd

In [4]:
import sys
import os

# Add the project root (one folder up from notebooks)
project_root = os.path.abspath('..')  # /home/lamel/rent-prediction-zoomcamp-mlops
if project_root not in sys.path:
    sys.path.append(project_root)

from mlpipeline.data_preparation import load_and_prepare_data

In [ ]:
# 1. Import necessary libs and your preprocessing functions
import pandas as pd
import mlflow.pyfunc

# Import your existing preprocessing pipeline functions
from mlpipeline.data_preparation import load_and_prepare_data  # or your specific preprocessing funcs
DATA_PATH = '../data/inference_data.csv'


# 3. Reuse your pipeline preprocessing function on inference data
# For example, if load_and_prepare_data does all preprocessing:
test_sample_processed = load_and_prepare_data(DATA_PATH)

# Optional: Print columns to debug
print("Available columns before drop:", test_sample_processed.columns.tolist())

# Safe drop
if 'Radiation' in test_sample_processed.columns:
    test_sample_processed.drop('Radiation', axis=1, inplace=True)
    print("Column 'Radiation' dropped.")
else:
    print("Column 'Radiation' not found. Skipping drop.")

# 4. Load champion model from MLflow
model_uri = "models:/MyTopModel/4"
model = mlflow.pyfunc.load_model(model_uri)

# 5. Predict on preprocessed data
predictions = model.predict(test_sample_processed)

# 6. Combine predictions with data and inspect
test_sample_processed['predictions'] = predictions
print(test_sample_processed.head())

10:41:35.230 | INFO    | Flow run 'greedy-asp' - Beginning flow run 'greedy-asp' for flow 'Load and Prepare Data Pipeline'

10:41:35.234 | INFO    | Flow run 'greedy-asp' - View at http://127.0.0.1:4200/runs/flow-run/c941c15d-143d-4277-acee-881ae8485c65

10:41:35.237 | INFO    | Flow run 'greedy-asp' - Starting the full data load and preparation pipeline

10:41:35.337 | INFO    | Task run 'Load Data from Local-71e' - Loading data from local path: ../data/inference_data.csv

10:41:35.371 | INFO    | Task run 'Load Data from Local-71e' - Finished in state Completed()

10:41:35.482 | INFO    | Task run 'Clean Data-013' - Cleaning data: removing duplicates and dropping all-NA rows

10:41:35.502 | INFO    | Task run 'Clean Data-013' - Data cleaned: (6538, 12) -> (6538, 12)

10:41:35.515 | INFO    | Task run 'Clean Data-013' - Finished in state Completed()

10:41:35.626 | INFO    | Task run 'Feature Engineering-ffc' - Starting feature engineering

10:41:35.682 | INFO    | Task run 'Feature Engineering-ffc' - Feature engineering completed. Data now has columns: ['Radiation', 'Temperature', 'Pressure', 'Humidity', 'WindDirection(Degrees)', 'Speed', 'Hour_sin', 'Hour_cos', 'Minute_sin', 'Minute_cos', 'Day_sin', 'Day_cos', 'Month_sin', 'Month_cos', 'Weekday_sin', 'Weekday_cos', 'MinutesSinceSunrise', 'MinutesUntilSunset']

10:41:35.690 | INFO    | Task run 'Feature Engineering-ffc' - Finished in state Completed()

10:41:35.697 | INFO    | Flow run 'greedy-asp' - Pipeline completed

10:41:35.765 | INFO    | Flow run 'greedy-asp' - Finished in state Completed()

Available columns before drop: ['Radiation', 'Temperature', 'Pressure', 'Humidity', 'WindDirection(Degrees)', 'Speed', 'Hour_sin', 'Hour_cos', 'Minute_sin', 'Minute_cos', 'Day_sin', 'Day_cos', 'Month_sin', 'Month_cos', 'Weekday_sin', 'Weekday_cos', 'MinutesSinceSunrise', 'MinutesUntilSunset']
Column 'Radiation' dropped.
   Temperature  Pressure  Humidity  WindDirection(Degrees)  Speed  Hour_sin  \
0           48     30.38        89                  247.97   7.87 -0.707107
1           48     30.38        88                  231.87   6.75 -0.866025
2           48     30.37        88                  226.78   5.62 -0.866025
3           48     30.37        88                  233.84   6.75 -0.866025
4           48     30.37        89                  223.11   6.75 -0.866025

   Hour_cos  Minute_sin    Minute_cos   Day_sin   Day_cos     Month_sin  \
0 -0.707107   -0.500000  8.660254e-01  0.968077 -0.250653 -2.449294e-16
1 -0.500000    0.000000  1.000000e+00  0.968077 -0.250653 -2.449294e-16
2 -0.500000    0.500000  8.660254e-01  0.968077 -0.250653 -2.449294e-16
3 -0.500000    0.866025  5.000000e-01  0.968077 -0.250653 -2.449294e-16
4 -0.500000    1.000000  2.832769e-16  0.968077 -0.250653 -2.449294e-16

   Month_cos  Weekday_sin  Weekday_cos  MinutesSinceSunrise  \
0        1.0    -0.433884    -0.900969           549.866667
1        1.0    -0.433884    -0.900969           554.816667
2        1.0    -0.433884    -0.900969           559.650000
3        1.0    -0.433884    -0.900969           564.850000
4        1.0    -0.433884    -0.900969           569.816667

   MinutesUntilSunset  predictions
0          108.133333       1.2699
1          103.183333       1.2546
2           98.350000       1.2548
3           93.150000       1.2566
4           88.183333       1.2632

In [18]:
from mlflow.tracking import MlflowClient

client = MlflowClient()
model_name = "MyTopModel"
versions = client.search_model_versions(f"name='{model_name}'")

for v in versions:
    print(f"Version: {v.version}, Stage: {v.current_stage}, Tags: {v.tags}")

Version: 4, Stage: None, Tags: {'model_type': 'RandomForest', 'test_rmse': '75.87197779365897', 'model_framework': 'RandomForest', 'status': 'production'}
Version: 3, Stage: None, Tags: {'model_type': 'RandomForest', 'test_rmse': '76.42694744217617', 'test_r2': '0.9457646068624453', 'model_framework': 'RandomForest', 'status': 'archived'}
Version: 2, Stage: Production, Tags: {'model_type': 'RandomForest', 'test_rmse': '76.0566347733126', 'test_r2': '0.9462889087497673', 'model_framework': 'RandomForest'}
Version: 1, Stage: None, Tags: {'model_type': 'RandomForest', 'test_rmse': '76.18648735881469', 'test_r2': '0.9461053487502389', 'model_framework': 'RandomForest'}

In [19]:
import mlflow
print("Tracking URI:", mlflow.get_tracking_uri())

Tracking URI: http://localhost:5000

In [23]:
test_sample=inference_df[:10]

In [ ]:
# to test model(has no target)
test_sample.to_csv('test_sample.csv', index=False)

In [ ]:
# for retraing
inference_df.to_csv('../training_data_v2.csv', index=False)

In [3]:
import mlflow

In [4]:
mlflow.set_tracking_uri("http://localhost:5000/")

In [1]:
from mlflow.tracking import MlflowClient

client = MlflowClient()
model_name = "MyTopModel"

# Get all versions of this model
versions = client.search_model_versions(f"name='{model_name}'")

# Delete each version
for v in versions:
    client.delete_model_version(name=model_name, version=v.version)

# Delete the registered model itself
client.delete_registered_model(name=model_name)

In [14]:
from mlflow.tracking import MlflowClient

client = MlflowClient()
experiment_ids = [exp.experiment_id for exp in client.list_experiments()]

for exp_id in experiment_ids:
    runs = client.search_runs(exp_id)
    for run in runs:
        client.delete_run(run.info.run_id)

AttributeError: 'MlflowClient' object has no attribute 'list_experiments'

In [19]:

import mlflow
experiments = mlflow.search_experiments()
for exp in experiments:
    print(exp.experiment_id, exp.name)

1 My_Model_Experiment
0 Default

In [8]:
import pandas as pd
from supabase import create_client, Client

SUPABASE_URL = "https://ccfmfqtlizzbaxlshzbu.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjZm1mcXRsaXp6YmF4bHNoemJ1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MjY2NzQwMiwiZXhwIjoyMDY4MjQzNDAyfQ.oa_2mmgazvIaiDk8BnymXiXZACb0iLRGmnnlGS0xhhE"
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# Load baseline
baseline = pd.read_csv('../data/training_data.csv')
print("Baseline dtypes:\n", baseline.dtypes)

# Fetch recent
response = supabase.table("model_logs").select("*").limit(500).execute()
recent = pd.DataFrame(response.data)
print("\nRecent dtypes:\n", recent.dtypes)

# Compare columns
print("\nCommon columns:", set(baseline.columns) & set(recent.columns))

Baseline dtypes:
 UNIXTime                   int64
Data                      object
Time                      object
Radiation                float64
Temperature                int64
Pressure                 float64
Humidity                   int64
WindDirection_Degrees    float64
Speed                    float64
TimeSunRise               object
TimeSunSet                object
datetime                  object
dtype: object

Recent dtypes:
 UNIXTime                   int64
Data                      object
Time                      object
Radiation                float64
Temperature                int64
Pressure                 float64
Humidity                   int64
WindDirection_Degrees    float64
Speed                    float64
TimeSunRise               object
TimeSunSet                object
datetime                  object
id                         int64
dtype: object

Common columns: {'UNIXTime', 'Time', 'Temperature', 'Pressure', 'datetime', 'Speed', 'Data', 'WindDirection_Degrees', 'Radiation', 'TimeSunRise', 'TimeSunSet', 'Humidity'}

In [16]:
import pandas as pd
from supabase import create_client, Client

SUPABASE_URL = "https://ccfmfqtlizzbaxlshzbu.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjZm1mcXRsaXp6YmF4bHNoemJ1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MjY2NzQwMiwiZXhwIjoyMDY4MjQzNDAyfQ.oa_2mmgazvIaiDk8BnymXiXZACb0iLRGmnnlGS0xhhE"
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

baseline = pd.read_csv('../data/df_short.csv')

def fetch_recent_data():
    response = supabase.table("model_logs").select("*").limit(1000).execute()
    data = response.data
    return pd.DataFrame(data)

recent = fetch_recent_data()

common_cols = [col for col in baseline.columns if col in recent.columns and col not in ['id', 'datetime']]
baseline_aligned = baseline[common_cols]
recent_aligned = recent[common_cols]

print("\n=== Data Types Comparison ===")
print(pd.DataFrame({
    'Baseline': baseline_aligned.dtypes,
    'Recent': recent_aligned.dtypes
}))

print("\n=== Null Counts in Recent Data ===")
print(recent_aligned.isnull().sum())

print("\n=== Baseline Data Sample ===")
print(baseline_aligned.head())

print("\n=== Recent Data Sample ===")
print(recent_aligned.head())

print("\n=== Are DataFrames Equal? ===")
print(baseline_aligned.equals(recent_aligned))

print("\n=== Baseline Summary Stats ===")
print(baseline_aligned.describe(include='all'))

print("\n=== Recent Summary Stats ===")
print(recent_aligned.describe(include='all'))

print("\n=== Column-wise Differences ===")
for col in common_cols:
    if not baseline_aligned[col].equals(recent_aligned[col]):
        print(f"\nColumn: {col}")
        print("Baseline unique values:", baseline_aligned[col].unique())
        print("Recent unique values:", recent_aligned[col].unique())

=== Data Types Comparison ===
                      Baseline   Recent
UNIXTime                 int64    int64
Data                    object   object
Time                    object   object
Radiation              float64  float64
Temperature              int64    int64
Pressure               float64  float64
Humidity                 int64    int64
WindDirection_Degrees  float64  float64
Speed                  float64  float64
TimeSunRise             object   object
TimeSunSet              object   object

=== Null Counts in Recent Data ===
UNIXTime                 0
Data                     0
Time                     0
Radiation                0
Temperature              0
Pressure                 0
Humidity                 0
WindDirection_Degrees    0
Speed                    0
TimeSunRise              0
TimeSunSet               0
dtype: int64

=== Baseline Data Sample ===
     UNIXTime                  Data      Time  Radiation  Temperature  \
0  1472724008  9/1/2016 12:00:00 AM  00:00:08       2.58           51
1  1472724310  9/1/2016 12:00:00 AM  00:05:10       2.83           51
2  1472725206  9/1/2016 12:00:00 AM  00:20:06       2.16           51
3  1472725505  9/1/2016 12:00:00 AM  00:25:05       2.21           51
4  1472725809  9/1/2016 12:00:00 AM  00:30:09       2.25           51

   Pressure  Humidity  WindDirection_Degrees  Speed TimeSunRise TimeSunSet
0     30.43       103                  77.27  11.25    06:07:00   18:38:00
1     30.43       103                 153.44   9.00    06:07:00   18:38:00
2     30.43       103                 142.04   7.87    06:07:00   18:38:00
3     30.43       103                 144.12  18.00    06:07:00   18:38:00
4     30.43       103                  67.42  11.25    06:07:00   18:38:00

=== Recent Data Sample ===
     UNIXTime                  Data      Time  Radiation  Temperature  \
0  1472724008  9/1/2016 12:00:00 AM  00:00:08       2.58           51
1  1472724310  9/1/2016 12:00:00 AM  00:05:10       2.83           51
2  1472725206  9/1/2016 12:00:00 AM  00:20:06       2.16           51
3  1472725505  9/1/2016 12:00:00 AM  00:25:05       2.21           51
4  1472725809  9/1/2016 12:00:00 AM  00:30:09       2.25           51

   Pressure  Humidity  WindDirection_Degrees  Speed TimeSunRise TimeSunSet
0     30.43       103                  77.27  11.25    06:07:00   18:38:00
1     30.43       103                 153.44   9.00    06:07:00   18:38:00
2     30.43       103                 142.04   7.87    06:07:00   18:38:00
3     30.43       103                 144.12  18.00    06:07:00   18:38:00
4     30.43       103                  67.42  11.25    06:07:00   18:38:00

=== Are DataFrames Equal? ===
True

=== Baseline Summary Stats ===
            UNIXTime                  Data      Time    Radiation  \
count   1.000000e+03                  1000      1000  1000.000000
unique           NaN                     4       836          NaN
top              NaN  9/3/2016 12:00:00 AM  04:15:04          NaN
freq             NaN                   282         4          NaN
mean    1.472887e+09                   NaN       NaN   244.525780
std     9.054345e+04                   NaN       NaN   349.924829
min     1.472724e+09                   NaN       NaN     1.570000
25%     1.472810e+09                   NaN       NaN     2.590000
50%     1.472888e+09                   NaN       NaN    18.445000
75%     1.472964e+09                   NaN       NaN   398.422500
max     1.473042e+09                   NaN       NaN  1601.260000

        Temperature     Pressure     Humidity  WindDirection_Degrees  \
count   1000.000000  1000.000000  1000.000000            1000.000000
unique          NaN          NaN          NaN                    NaN
top             NaN          NaN          NaN                    NaN
freq            NaN          NaN          NaN                    NaN
mean      55.362000    30.443500    84.497000             136.592420
std        4.619989     0.021157    17.255716              86.433862
min       46.000000    30.400000    28.000000               0.590000
25%       51.000000    30.430000    73.000000              67.420000
50%       55.000000    30.440000    92.000000             135.985000
75%       59.000000    30.460000    98.000000             175.592500
max       65.000000    30.490000   103.000000             359.370000

              Speed TimeSunRise TimeSunSet
count   1000.000000        1000       1000
unique          NaN           2          4
top             NaN    06:07:00   18:36:00
freq            NaN         529        282
mean       5.647290         NaN        NaN
std        3.036006         NaN        NaN
min        0.000000         NaN        NaN
25%        3.370000         NaN        NaN
50%        5.620000         NaN        NaN
75%        7.870000         NaN        NaN
max       18.000000         NaN        NaN

=== Recent Summary Stats ===
            UNIXTime                  Data      Time    Radiation  \
count   1.000000e+03                  1000      1000  1000.000000
unique           NaN                     4       836          NaN
top              NaN  9/3/2016 12:00:00 AM  04:15:04          NaN
freq             NaN                   282         4          NaN
mean    1.472887e+09                   NaN       NaN   244.525780
std     9.054345e+04                   NaN       NaN   349.924829
min     1.472724e+09                   NaN       NaN     1.570000
25%     1.472810e+09                   NaN       NaN     2.590000
50%     1.472888e+09                   NaN       NaN    18.445000
75%     1.472964e+09                   NaN       NaN   398.422500
max     1.473042e+09                   NaN       NaN  1601.260000

        Temperature     Pressure     Humidity  WindDirection_Degrees  \
count   1000.000000  1000.000000  1000.000000            1000.000000
unique          NaN          NaN          NaN                    NaN
top             NaN          NaN          NaN                    NaN
freq            NaN          NaN          NaN                    NaN
mean      55.362000    30.443500    84.497000             136.592420
std        4.619989     0.021157    17.255716              86.433862
min       46.000000    30.400000    28.000000               0.590000
25%       51.000000    30.430000    73.000000              67.420000
50%       55.000000    30.440000    92.000000             135.985000
75%       59.000000    30.460000    98.000000             175.592500
max       65.000000    30.490000   103.000000             359.370000

              Speed TimeSunRise TimeSunSet
count   1000.000000        1000       1000
unique          NaN           2          4
top             NaN    06:07:00   18:36:00
freq            NaN         529        282
mean       5.647290         NaN        NaN
std        3.036006         NaN        NaN
min        0.000000         NaN        NaN
25%        3.370000         NaN        NaN
50%        5.620000         NaN        NaN
75%        7.870000         NaN        NaN
max       18.000000         NaN        NaN

=== Column-wise Differences ===

In [17]:
import hashlib

def df_hash(df):
    return hashlib.md5(pd.util.hash_pandas_object(df, index=True).values).hexdigest()

print("Baseline hash:", df_hash(baseline_aligned))
print("Recent hash:", df_hash(recent_aligned))

Baseline hash: a60bba92f883e2f0d10cfeb7ab2991d7
Recent hash: a60bba92f883e2f0d10cfeb7ab2991d7

In [18]:
import json
from prometheus_client import start_http_server, Gauge
from evidently.report import Report
from evidently.metric_preset import DataDriftPreset
import pandas as pd
import time
from supabase import create_client, Client
import os
import numpy as np
import random



if df_hash(baseline_aligned) == df_hash(recent_aligned):
    print("Data identical. Forcing drift share to 0.")
    drift_share = 0.0
    per_column_drift = {col: False for col in baseline_aligned.columns}
else:
    report = Report(metrics=[DataDriftPreset()])
    report.run(reference_data=baseline_aligned, current_data=recent_aligned)
    result = report.as_dict()
    drift_share = result['metrics'][0]['result'].get('share_of_drifted_columns', 0.0)
    per_column_drift = {
        col: details['drift_detected']
        for col, details in result['metrics'][0]['result']['drift_by_columns'].items()
    }

print(f"Updated data drift share: {drift_share}")
print("Per-column drift status:")
print(json.dumps(per_column_drift, indent=2))

Data identical. Forcing drift share to 0.
Updated data drift share: 0.0
Per-column drift status:
{
  "UNIXTime": false,
  "Data": false,
  "Time": false,
  "Radiation": false,
  "Temperature": false,
  "Pressure": false,
  "Humidity": false,
  "WindDirection_Degrees": false,
  "Speed": false,
  "TimeSunRise": false,
  "TimeSunSet": false
}

In [52]:
df = pd.read_csv('../data/SolarPrediction.csv')

In [53]:
df.shape

(32686, 11)

In [54]:
df.head(25)

,UNIXTime,Data,Time,Radiation,Temperature,Pressure,Humidity,WindDirection_Degrees,Speed,TimeSunRise,TimeSunSet
0,1475229326,9/29/2016 12:00:00 AM,23:55:26,1.21,48,30.46,59,177.39,5.62,06:13:00,18:13:00
1,1475229023,9/29/2016 12:00:00 AM,23:50:23,1.21,48,30.46,58,176.78,3.37,06:13:00,18:13:00
2,1475228726,9/29/2016 12:00:00 AM,23:45:26,1.23,48,30.46,57,158.75,3.37,06:13:00,18:13:00
3,1475228421,9/29/2016 12:00:00 AM,23:40:21,1.21,48,30.46,60,137.71,3.37,06:13:00,18:13:00
4,1475228124,9/29/2016 12:00:00 AM,23:35:24,1.17,48,30.46,62,104.95,5.62,06:13:00,18:13:00
5,1475227824,9/29/2016 12:00:00 AM,23:30:24,1.21,48,30.46,64,120.20,5.62,06:13:00,18:13:00
6,1475227519,9/29/2016 12:00:00 AM,23:25:19,1.20,49,30.46,72,112.45,6.75,06:13:00,18:13:00
7,1475227222,9/29/2016 12:00:00 AM,23:20:22,1.24,49,30.46,71,122.97,5.62,06:13:00,18:13:00
8,1475226922,9/29/2016 12:00:00 AM,23:15:22,1.23,49,30.46,80,101.18,4.50,06:13:00,18:13:00
9,1475226622,9/29/2016 12:00:00 AM,23:10:22,1.21,49,30.46,85,141.87,4.50,06:13:00,18:13:00
10,1475226323,9/29/2016 12:00:00 AM,23:05:23,1.23,49,30.47,93,120.55,2.25,06:13:00,18:13:00
11,1475226025,9/29/2016 12:00:00 AM,23:00:25,1.21,49,30.47,98,144.19,3.37,06:13:00,18:13:00
12,1475225720,9/29/2016 12:00:00 AM,22:55:20,1.22,49,30.47,99,139.80,6.75,06:13:00,18:13:00
13,1475225419,9/29/2016 12:00:00 AM,22:50:19,1.21,50,30.47,99,140.92,2.25,06:13:00,18:13:00
14,1475225131,9/29/2016 12:00:00 AM,22:45:31,1.23,50,30.47,99,147.61,5.62,06:13:00,18:13:00
15,1475224823,9/29/2016 12:00:00 AM,22:40:23,1.22,50,30.47,99,113.78,4.50,06:13:00,18:13:00
16,1475224519,9/29/2016 12:00:00 AM,22:35:19,1.21,50,30.47,99,123.03,10.12,06:13:00,18:13:00
17,1475224222,9/29/2016 12:00:00 AM,22:30:22,1.22,50,30.47,99,173.73,6.75,06:13:00,18:13:00
18,1475223919,9/29/2016 12:00:00 AM,22:25:19,1.22,50,30.47,98,91.43,6.75,06:13:00,18:13:00
19,1475223622,9/29/2016 12:00:00 AM,22:20:22,1.20,50,30.47,98,109.74,6.75,06:13:00,18:13:00
20,1475223322,9/29/2016 12:00:00 AM,22:15:22,1.20,50,30.47,98,143.53,2.25,06:13:00,18:13:00
21,1475223021,9/29/2016 12:00:00 AM,22:10:21,1.20,50,30.47,97,146.76,5.62,06:13:00,18:13:00
22,1475222720,9/29/2016 12:00:00 AM,22:05:20,1.21,50,30.47,97,158.35,4.50,06:13:00,18:13:00
23,1475222426,9/29/2016 12:00:00 AM,22:00:26,1.22,50,30.47,97,166.05,5.62,06:13:00,18:13:00
24,1475222120,9/29/2016 12:00:00 AM,21:55:20,1.22,50,30.47,96,151.82,5.62,06:13:00,18:13:00

In [55]:
df['Dat3'] = pd.to_datetime(df['Data'])
is_sorted = df['Data'].is_monotonic_increasing
print(is_sorted)

/tmp/ipykernel_7113/3463318605.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dat3'] = pd.to_datetime(df['Data'])

False

In [56]:
df['Dat3'] = pd.to_datetime(df['Data'], format='%m/%d/%Y %I:%M:%S %p')

In [57]:
df = df.sort_values('Dat3').reset_index(drop=True)

In [58]:
df

,UNIXTime,Data,Time,Radiation,Temperature,Pressure,Humidity,WindDirection_Degrees,Speed,TimeSunRise,TimeSunSet,Dat3
0,1472793006,9/1/2016 12:00:00 AM,19:10:06,2.53,55,30.45,65,155.71,3.37,06:07:00,18:38:00,2016-09-01
1,1472781308,9/1/2016 12:00:00 AM,15:55:08,628.80,63,30.42,58,1.55,6.75,06:07:00,18:38:00,2016-09-01
2,1472781606,9/1/2016 12:00:00 AM,16:00:06,596.57,62,30.42,56,81.70,5.62,06:07:00,18:38:00,2016-09-01
3,1472781907,9/1/2016 12:00:00 AM,16:05:07,577.10,62,30.42,57,53.61,7.87,06:07:00,18:38:00,2016-09-01
4,1472782211,9/1/2016 12:00:00 AM,16:10:11,573.13,62,30.42,58,14.04,3.37,06:07:00,18:38:00,2016-09-01
...,...,...,...,...,...,...,...,...,...,...,...,...
32681,1483206901,12/31/2016 12:00:00 AM,07:55:01,39.30,43,30.31,86,262.51,5.62,06:57:00,17:54:00,2016-12-31
32682,1483206602,12/31/2016 12:00:00 AM,07:50:02,39.51,42,30.31,85,265.53,7.87,06:57:00,17:54:00,2016-12-31
32683,1483206302,12/31/2016 12:00:00 AM,07:45:02,52.87,42,30.31,84,240.48,4.50,06:57:00,17:54:00,2016-12-31
32684,1483221902,12/31/2016 12:00:00 AM,12:05:02,378.41,53,30.33,68,321.95,10.12,06:57:00,17:54:00,2016-12-31
32685,1483178408,12/31/2016 12:00:00 AM,00:00:08,1.21,44,30.33,92,278.07,5.62,06:57:00,17:54:00,2016-12-31

In [59]:
df_sample = df.head(6000)

In [62]:
df_sample.drop(columns='Dat3', inplace=True)

In [63]:
train_size = int(0.8 * len(df_sample))

df1 = df_sample.iloc[:train_size]
df2 = df_sample.iloc[train_size:]

In [64]:
df1.to_csv('../data/training_data.csv',index=False)
df2.to_csv('../data/new_data/new_data.csv',index=False)

In [67]:
df2.to_csv('../data/inference_data.csv',index=False)

In [65]:
df2.drop('Radiation',axis=1, inplace=True)

In [66]:
df2

,UNIXTime,Data,Time,Temperature,Pressure,Humidity,WindDirection_Degrees,Speed,TimeSunRise,TimeSunSet
4800,1474375505,9/20/2016 12:00:00 AM,02:45:05,47,30.40,36,170.09,6.75,06:11:00,18:21:00
4801,1474375202,9/20/2016 12:00:00 AM,02:40:02,47,30.40,37,181.27,5.62,06:11:00,18:21:00
4802,1474374905,9/20/2016 12:00:00 AM,02:35:05,48,30.40,37,177.29,6.75,06:11:00,18:21:00
4803,1474374603,9/20/2016 12:00:00 AM,02:30:03,48,30.40,39,177.76,6.75,06:11:00,18:21:00
4804,1474371604,9/20/2016 12:00:00 AM,01:40:04,49,30.41,45,175.54,5.62,06:11:00,18:21:00
...,...,...,...,...,...,...,...,...,...,...
5995,1474735822,9/24/2016 12:00:00 AM,06:50:22,49,30.46,94,174.31,4.50,06:12:00,18:17:00
5996,1474735219,9/24/2016 12:00:00 AM,06:40:19,49,30.45,93,171.42,4.50,06:12:00,18:17:00
5997,1474734920,9/24/2016 12:00:00 AM,06:35:20,49,30.45,93,176.43,3.37,06:12:00,18:17:00
5998,1474734619,9/24/2016 12:00:00 AM,06:30:19,49,30.45,93,176.83,5.62,06:12:00,18:17:00
5999,1474734320,9/24/2016 12:00:00 AM,06:25:20,49,30.45,93,174.47,5.62,06:12:00,18:17:00

In [75]:
df = pd.read_csv('../data/training_data.csv')

In [76]:
df

,UNIXTime,Data,Time,Radiation,Temperature,Pressure,Humidity,WindDirection_Degrees,Speed,TimeSunRise,TimeSunSet
0,1472793006,9/1/2016 12:00:00 AM,19:10:06,2.53,55,30.45,65,155.71,3.37,06:07:00,18:38:00
1,1472781308,9/1/2016 12:00:00 AM,15:55:08,628.80,63,30.42,58,1.55,6.75,06:07:00,18:38:00
2,1472781606,9/1/2016 12:00:00 AM,16:00:06,596.57,62,30.42,56,81.70,5.62,06:07:00,18:38:00
3,1472781907,9/1/2016 12:00:00 AM,16:05:07,577.10,62,30.42,57,53.61,7.87,06:07:00,18:38:00
4,1472782211,9/1/2016 12:00:00 AM,16:10:11,573.13,62,30.42,58,14.04,3.37,06:07:00,18:38:00
...,...,...,...,...,...,...,...,...,...,...,...
4795,1474387204,9/20/2016 12:00:00 AM,06:00:04,1.98,48,30.39,32,103.18,2.25,06:11:00,18:21:00
4796,1474371302,9/20/2016 12:00:00 AM,01:35:02,1.22,50,30.41,43,171.95,5.62,06:11:00,18:21:00
4797,1474371905,9/20/2016 12:00:00 AM,01:45:05,1.22,49,30.41,46,181.73,6.75,06:11:00,18:21:00
4798,1474376102,9/20/2016 12:00:00 AM,02:55:02,1.29,47,30.40,38,160.78,6.75,06:11:00,18:21:00
4799,1474375804,9/20/2016 12:00:00 AM,02:50:04,1.23,47,30.40,37,177.52,9.00,06:11:00,18:21:00

In [71]:
df1

,UNIXTime,Data,Time,Radiation,Temperature,Pressure,Humidity,WindDirection_Degrees,Speed,TimeSunRise,TimeSunSet
0,1472793006,9/1/2016 12:00:00 AM,19:10:06,2.53,55,30.45,65,155.71,3.37,06:07:00,18:38:00
1,1472781308,9/1/2016 12:00:00 AM,15:55:08,628.80,63,30.42,58,1.55,6.75,06:07:00,18:38:00
2,1472781606,9/1/2016 12:00:00 AM,16:00:06,596.57,62,30.42,56,81.70,5.62,06:07:00,18:38:00
3,1472781907,9/1/2016 12:00:00 AM,16:05:07,577.10,62,30.42,57,53.61,7.87,06:07:00,18:38:00
4,1472782211,9/1/2016 12:00:00 AM,16:10:11,573.13,62,30.42,58,14.04,3.37,06:07:00,18:38:00
...,...,...,...,...,...,...,...,...,...,...,...
4795,1474387204,9/20/2016 12:00:00 AM,06:00:04,1.98,48,30.39,32,103.18,2.25,06:11:00,18:21:00
4796,1474371302,9/20/2016 12:00:00 AM,01:35:02,1.22,50,30.41,43,171.95,5.62,06:11:00,18:21:00
4797,1474371905,9/20/2016 12:00:00 AM,01:45:05,1.22,49,30.41,46,181.73,6.75,06:11:00,18:21:00
4798,1474376102,9/20/2016 12:00:00 AM,02:55:02,1.29,47,30.40,38,160.78,6.75,06:11:00,18:21:00
4799,1474375804,9/20/2016 12:00:00 AM,02:50:04,1.23,47,30.40,37,177.52,9.00,06:11:00,18:21:00

In [72]:
df1['Radiation'].max()

np.float64(1601.26)

In [2]:
from dotenv import load_dotenv
import os
load_dotenv()
print(os.getenv("S3_BUCKET_NAME"))

model-data-bucket-4821# AWS_DEFAULT_REGION=us-east-1

In [8]:
import pandas as pd

df = pd.read_csv("../data/SolarPrediction.csv")

df.head()

,UNIXTime,Data,Time,Radiation,Temperature,Pressure,Humidity,WindDirection(Degrees),Speed,TimeSunRise,TimeSunSet
0,1475229326,9/29/2016 12:00:00 AM,23:55:26,1.21,48,30.46,59,177.39,5.62,06:13:00,18:13:00
1,1475229023,9/29/2016 12:00:00 AM,23:50:23,1.21,48,30.46,58,176.78,3.37,06:13:00,18:13:00
2,1475228726,9/29/2016 12:00:00 AM,23:45:26,1.23,48,30.46,57,158.75,3.37,06:13:00,18:13:00
3,1475228421,9/29/2016 12:00:00 AM,23:40:21,1.21,48,30.46,60,137.71,3.37,06:13:00,18:13:00
4,1475228124,9/29/2016 12:00:00 AM,23:35:24,1.17,48,30.46,62,104.95,5.62,06:13:00,18:13:00

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32686 entries, 0 to 32685
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   UNIXTime                32686 non-null  int64
 1   Data                    32686 non-null  object
 2   Time                    32686 non-null  object
 3   Radiation               32686 non-null  float64
 4   Temperature             32686 non-null  int64
 5   Pressure                32686 non-null  float64
 6   Humidity                32686 non-null  int64
 7   WindDirection(Degrees)  32686 non-null  float64
 8   Speed                   32686 non-null  float64
 9   TimeSunRise             32686 non-null  object
 10  TimeSunSet              32686 non-null  object
dtypes: float64(4), int64(3), object(4)
memory usage: 2.7+ MB

np.int64(0)